### ISSUE TITLE
Trade drop down blank

### ISSUE THREAD

**Issue by Saitaina** [filler00/etcg#10]
I was trying to test my trade.php page before I add it to the site and the drop down to select a TCG is blank: http://www.tcr.moricia.com/trade.php  I have five active tcg's on etcg so I have no idea.

**Comment by tooblue** [comment]
Make sure you're using the latest 'func.php' file from here: https://github.com/tooblue/etcg/blob/master/func.php

Let me know if it's still showing up blank~

**Comment by Saitaina** [comment]
That worked, but now I have to try to figure out what edits are in my old func.php that fixed my website the first time around.

Sait

**Comment by tooblue** [comment]
You can use something like https://www.diffchecker.com/ to compare your old file to the new one. I can also take a look for you if you attach the file! :)
